name: 1. Create Terraform Backend

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type: CREATE BACKEND'
        required: true
        default: ''

jobs:
  create-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.event.inputs.confirm == 'CREATE BACKEND'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Create S3 + DynamoDB
        run: |
          cd infra/terraform/backend
          terraform init
          terraform apply -auto-approve
          echo "Backend bucket: ${{ secrets.TF_BACKEND_BUCKET }}"
          echo "Lock table: ${{ secrets.TF_BACKEND_TABLE }}"
