name: 2. Create VPC + EKS

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type: CREATE INFRA'
        required: true
        default: ''

jobs:
  create-infra:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.event.inputs.confirm == 'CREATE INFRA'

    steps:
      # -------------------------------------------------
      # 0. Checkout & AWS auth
      # -------------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      # -------------------------------------------------
      # 1. CLEAN LOCAL STATE (CRITICAL)
      # -------------------------------------------------
      - name: Clean Local Terraform State
        run: |
          cd infra/terraform/app
          rm -rf .terraform* *.tfstate *.tfstate.backup
          echo "Local state deleted — will use S3 backend"

      # -------------------------------------------------
      # 2. INIT WITH S3 BACKEND
      # -------------------------------------------------
      - name: Terraform Init (S3 Backend)
        run: |
          cd infra/terraform/app
          echo "Initializing Terraform with S3 backend..."
          terraform init \
            -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
            -backend-config="key=eks/app.tfstate" \
            -backend-config="dynamodb_table=${{ secrets.TF_BACKEND_TABLE }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -reconfigure

          echo "Backend configured. State will be stored in S3."

      # -------------------------------------------------
      # 3. TERRAFORM APPLY WITH AUTO-IMPORT ON CONFLICT
      # -------------------------------------------------
      - name: Terraform Apply (with Auto-Import)
        run: |
          cd infra/terraform/app

          echo "Running terraform apply..."
          set +e
          terraform apply -auto-approve \
            -var="cluster_name=${{ secrets.EKS_CLUSTER_NAME }}" \
            > apply.log 2>&1
          TF_EXIT=$?
          set -e

          # If apply failed due to AlreadyExists → import and retry
          if grep -q "EntityAlreadyExists\|AlreadyExistsException" apply.log; then
            echo "Detected existing resources in AWS. Importing into Terraform state..."

            # --- Import IAM User ---
            if grep -q "aws_iam_user.admin" apply.log; then
              USER_NAME=$(grep -o "User with name [^ ]*" apply.log | awk '{print $4}')
              echo "Importing IAM user: $USER_NAME"
              terraform import aws_iam_user.admin "$USER_NAME" || true
            fi

            # --- Import KMS Key & Alias ---
            if grep -q 'aws_kms_alias.this\["cluster"\]' apply.log; then
              ALIAS_NAME=$(grep -o 'alias/eks/[^ ]*' apply.log | head -1)
              KEY_ID=$(aws kms list-aliases \
                --query "Aliases[?AliasName=='arn:aws:kms:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:$ALIAS_NAME'].TargetKeyId" \
                --output text)
              if [[ -n "$KEY_ID" ]]; then
                echo "Importing KMS key: $KEY_ID"
                terraform import "module.eks_cluster.module.kms.aws_kms_key.this[\"cluster\"]" "$KEY_ID" || true
                echo "Importing KMS alias: $ALIAS_NAME"
                terraform import "module.eks_cluster.module.kms.aws_kms_alias.this[\"cluster\"]" "$ALIAS_NAME" || true
              fi
            fi

            # --- Import CloudWatch Log Group ---
            if grep -q 'aws_cloudwatch_log_group.this\[0\]' apply.log; then
              LOG_GROUP=$(grep -o '/aws/eks/[^ ]*/cluster' apply.log | head -1)
              echo "Importing log group: $LOG_GROUP"
              terraform import module.eks_cluster.aws_cloudwatch_log_group.this[0] "$LOG_GROUP" || true
            fi

            echo "Re-running terraform apply after import..."
            terraform apply -auto-approve -var="cluster_name=${{ secrets.EKS_CLUSTER_NAME }}"
          else
            if [ $TF_EXIT -ne 0 ]; then
              echo "Terraform apply failed:"
              cat apply.log
              exit $TF_EXIT
            fi
          fi

          echo "Terraform apply completed successfully."

      # -------------------------------------------------
      # 4. WAIT FOR EKS CLUSTER TO BE ACTIVE
      # -------------------------------------------------
      - name: Wait for EKS Cluster to be ACTIVE
        run: |
          echo "Waiting for EKS cluster '${{ secrets.EKS_CLUSTER_NAME }}' to become ACTIVE..."
          timeout=1200  # 20 minutes
          interval=30
          elapsed=0

          while [ $elapsed -lt $timeout ]; do
            STATUS=$(aws eks describe-cluster \
              --name ${{ secrets.EKS_CLUSTER_NAME }} \
              --region ${{ secrets.AWS_REGION }} \
              --query 'cluster.status' --output text 2>/dev/null || echo "NOT_FOUND")

            echo "Cluster status: $STATUS (elapsed: ${elapsed}s)"

            if [[ "$STATUS" == "ACTIVE" ]]; then
              echo "EKS CLUSTER IS ACTIVE!"
              break
            fi

            if [[ "$STATUS" == "FAILED" ]]; then
              echo "EKS CLUSTER CREATION FAILED"
              aws eks describe-cluster --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
              exit 1
            fi

            sleep $interval
            elapsed=$((elapsed + interval))
          done

          if [[ "$STATUS" != "ACTIVE" ]]; then
            echo "TIMEOUT: Cluster did not become ACTIVE in 20 minutes"
            exit 1
          fi

      # -------------------------------------------------
      # 5. RE-AUTH & KUBECTL
      # -------------------------------------------------
      - name: Reconfigure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          echo "kubectl installed"

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }} \
            --alias techv
          echo "Connected to EKS"
          kubectl get nodes

      # -------------------------------------------------
      # 6. POD IDENTITY AGENT
      # -------------------------------------------------
      - name: Install Pod Identity Agent
        run: |
          echo "Installing eks-pod-identity-agent..."
          aws eks create-addon \
            --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} \
            --addon-name eks-pod-identity-agent \
            --resolve-conflicts=OVERWRITE \
            || echo "Already installed"
          echo "Waiting 4 minutes..."
          sleep 240

      # -------------------------------------------------
      # 7. EBS CSI IAM ROLE (FULL IDEMPOTENT)
      # -------------------------------------------------
      - name: Create EBS CSI IAM Role
        run: |
          echo "Setting up IAM role for EBS CSI driver..."

          OIDC_ID=$(aws eks describe-cluster \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --query "cluster.identity.oidc.issuer" \
            --output text | cut -d '/' -f 5)

          OIDC_URL="arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:oidc-provider/oidc.eks.${{ secrets.AWS_REGION }}.amazonaws.com/id/$OIDC_ID"

          cat > ebs-trust-policy.json <<EOF
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": { "Federated": "$OIDC_URL" },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "oidc.eks.${{ secrets.AWS_REGION }}.amazonaws.com/id/$OIDC_ID:aud": "sts.amazonaws.com",
                    "oidc.eks.${{ secrets.AWS_REGION }}.amazonaws.com/id/$OIDC_ID:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
                  }
                }
              }
            ]
          }
          EOF

          ROLE_NAME="AmazonEKS_EBS_CSI_DriverRole_${{ secrets.EKS_CLUSTER_NAME }}"
          ROLE_ARN=$(aws iam get-role --role-name "$ROLE_NAME" --query 'Role.Arn' --output text 2>/dev/null || echo "")

          if [[ -z "$ROLE_ARN" ]]; then
            echo "Creating new IAM role..."
            ROLE_ARN=$(aws iam create-role \
              --role-name "$ROLE_NAME" \
              --assume-role-policy-document file://ebs-trust-policy.json \
              --query 'Role.Arn' --output text)
            echo "Created role: $ROLE_ARN"
          else
            echo "Using existing role: $ROLE_ARN"
          fi

          echo "Attaching AmazonEBSCSIDriverPolicy..."
          aws iam attach-role-policy \
            --policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
            --role-name "$ROLE_NAME" \
            || echo "Policy already attached"

          echo "ROLE_ARN=$ROLE_ARN" >> $GITHUB_ENV

      # -------------------------------------------------
      # 8. EBS CSI DRIVER + FULL WAIT LOOP
      # -------------------------------------------------
      - name: Install EBS CSI Driver
        run: |
          echo "Installing aws-ebs-csi-driver add-on..."
          aws eks create-addon \
            --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} \
            --addon-name aws-ebs-csi-driver \
            --service-account-role-arn ${{ env.ROLE_ARN }} \
            --resolve-conflicts=OVERWRITE \
            || echo "Already installed"

          echo "Waiting 5 minutes for controller to start..."
          sleep 300

          echo "Checking EBS CSI controller deployment..."
          for i in {1..12}; do
            if kubectl wait --for=condition=Available deployment/ebs-csi-controller -n kube-system --timeout=10s >/dev/null 2>&1; then
              echo "EBS CSI DRIVER READY"
              break
            fi
            echo "Controller not ready yet (attempt $i/12)..."
            sleep 10
          done

          if ! kubectl get deployment ebs-csi-controller -n kube-system >/dev/null 2>&1; then
            echo "EBS CSI controller deployment missing!"
            exit 1
          fi

      # -------------------------------------------------
      # 9. SUCCESS
      # -------------------------------------------------
      - name: Success
        run: |
          echo "EKS INFRA CREATION COMPLETE!"
          echo "Cluster: ${{ secrets.EKS_CLUSTER_NAME }}"
          echo "Region: ${{ secrets.AWS_REGION }}"
          echo "Next: Run '3. Deploy App'"